---
title: "R Notebook"
output: html_notebook
---
Preparing data
```{r}
library(data.table)
library(dplyr)
library(tidyr)


# Load Data ---------------------------------------------------------------
aisles <- fread("data/aisles.csv")
departments <- fread("data/departments.csv")
orderp <- fread("data/order_products__prior.csv")
ordert <- fread("data/order_products__train.csv")
orders <- fread("data/orders.csv")
products <- fread("data/products.csv")


# Reshape data ------------------------------------------------------------
aisles$aisle <- as.factor(aisles$aisle)
departments$department <- as.factor(departments$department)
orders$eval_set <- as.factor(orders$eval_set)
products$product_name <- as.factor(products$product_name)

products <- products %>% 
  inner_join(aisles) %>% inner_join(departments) %>%
  select(-aisle, -department)
rm(aisles, departments)

ordert$user_id <- orders$user_id[match(ordert$order_id, orders$order_id)]

orders_products <- orders %>% inner_join(orderp, by = "order_id")

orders_products <- orders_products %>% left_join(products, by = "product_id")

head(products)
head(orders_products)

rm(orderp)
gc()


# Products ----------------------------------------------------------------
prd <- orders_products %>%
  arrange(user_id, order_number, product_id) %>%
  group_by(user_id, product_id) %>%
  mutate(product_time = row_number()) %>%
  ungroup() %>%
  group_by(product_id) %>%
  summarise(
    prod_orders = n(),
    prod_distinct_buyers = n_distinct(user_id),
    prod_reorders = sum(reordered),
    prod_first_orders = sum(product_time == 1),
    prod_second_orders = sum(product_time == 2),
    prod_avg_dow = mean(order_dow),
    prod_avg_hour_of_day = mean(order_hour_of_day)
  )

prd$prod_reorder_probability <- prd$prod_second_orders / prd$prod_first_orders
prd$prod_reorder_times <- 1 + prd$prod_reorders / prd$prod_first_orders
prd$prod_reorder_ratio <- prd$prod_reorders / prd$prod_orders

prd <- prd %>% select(-prod_reorders, -prod_first_orders, -prod_second_orders)

rm(products)
gc()

# Users -------------------------------------------------------------------
users <- orders %>%
  filter(eval_set == "prior") %>%
  group_by(user_id) %>%
  summarise(
    user_orders = max(order_number),
    user_period = sum(days_since_prior_order, na.rm = T),
    user_mean_days_since_prior = mean(days_since_prior_order, na.rm = T),
    user_avg_dow = mean(order_dow),
    user_avg_hour_of_day = mean(order_hour_of_day)
  )

us <- orders_products %>%
  group_by(user_id) %>%
  summarise(
    user_total_products = n(),
    user_reorder_ratio = sum(reordered == 1) / sum(order_number > 1),
    user_distinct_products = n_distinct(product_id),
    user_distinct_aisles = n_distinct(aisle_id),
    user_distinct_departments = n_distinct(department_id)
  )

users <- users %>% inner_join(us)
users$user_average_basket <- users$user_total_products / users$user_orders

us <- orders %>%
  filter(eval_set != "prior") %>%
  select(user_id, order_id, eval_set,
         time_since_last_order = days_since_prior_order)

users <- users %>% inner_join(us)

rm(us)
gc()


# Database ----------------------------------------------------------------
data <- orders_products %>%
  group_by(user_id, product_id) %>% 
  summarise(
    up_orders = n(),
    up_first_order = min(order_number),
    up_last_order = max(order_number),
    up_average_cart_position = mean(add_to_cart_order),
    up_avg_dow = mean(order_dow),
    up_avg_hour_of_day = mean(order_hour_of_day))

rm(orders_products, orders)

data <- data %>% 
  inner_join(prd, by = "product_id") %>%
  inner_join(users, by = "user_id")

data$up_order_rate <- data$up_orders / data$user_orders
data$up_orders_since_last_order <- data$user_orders - data$up_last_order
data$up_order_rate_since_first_order <- data$up_orders / (data$user_orders - data$up_first_order + 1)

data <- data %>% 
  left_join(ordert %>% select(user_id, product_id, reordered), 
            by = c("user_id", "product_id"))

# Get rid of least influencial features
#data <- subset(data, select=-c(prod_reorder_ratio, up_avg_dow, up_avg_hour_of_day, user_orders))

head(data, 20)
nrow(data)

rm(ordert, prd, users)
gc()

```

Prepare train / test datasets (execute either this or or the chunk below)
```{r}
# Train / Test datasets ---------------------------------------------------
train <- as.data.frame(data[data$eval_set == "train",])
train$eval_set <- NULL
train$user_id <- NULL
train$product_id <- NULL
train$order_id <- NULL
train$reordered[is.na(train$reordered)] <- 0

test <- as.data.frame(data[data$eval_set == "test",])
test$eval_set <- NULL
test$user_id <- NULL
test$reordered <- NULL

train <- train %>% sample_frac(0.1)
rm(data)
gc()
```

Prepare train / test datasets for testing model
```{r}
# Train / Test datasets ---------------------------------------------------
# train_large <- as.data.frame(data[data$eval_set == "train",])
# 
# subdata <- train_large %>% sample_frac(0.1)
# smp_size <- floor(0.75 * nrow(subdata))
# set.seed(123)
# train_ind <- sample(seq_len(nrow(subdata)), size = smp_size)
# 
# train <- subdata[train_ind, ]
# test <- subdata[-train_ind, ]
# 
# train$eval_set <- NULL
# train$user_id <- NULL
# train$product_id <- NULL
# train$order_id <- NULL
# train$reordered[is.na(train$reordered)] <- 0
# 
# test$eval_set <- NULL
# test$user_id <- NULL
# test$reordered <- NULL
# 
# rm(data)
# gc()
```

Train model
```{r}
library(xgboost)

params <- list(
  "objective"           = "reg:logistic",
  "eval_metric"         = "logloss",
  "eta"                 = 0.1,
  "max_depth"           = 6,
  "min_child_weight"    = 10,
  "gamma"               = 0.70,
  "subsample"           = 0.76,
  "colsample_bytree"    = 0.95,
  "alpha"               = 2e-05,
  "lambda"              = 10
)

X <- xgb.DMatrix(as.matrix(train %>% select(-reordered)), label = train$reordered)
model <- xgboost(data = X, params = params, nrounds = 120)

importance <- xgb.importance(colnames(X), model = model)
xgb.ggplot.importance(importance)
print(importance)
rm(X, importance, train_large)
gc()

```

```{r}
# Apply model -------------------------------------------------------------
X <- xgb.DMatrix(as.matrix(test %>% select(-order_id, -product_id)))
test$reordered <- predict(model, X)

test$reordered <- (test$reordered > 0.21) * 1

submission <- test %>%
  filter(reordered == 1) %>%
  group_by(order_id) %>%
  summarise(
    products = paste(product_id, collapse = " ")
  )

missing <- data.frame(
  order_id = unique(test$order_id[!test$order_id %in% submission$order_id]),
  products = "None"
)

submission <- submission %>% bind_rows(missing) %>% arrange(order_id)

rm(missing)
gc()
```

Write results to file
```{r}
write.csv(submission, file = "submit.csv", row.names = F)
```

Find F1 score
```{r}
# Reading in the files
orders <- fread('data/orders.csv')
order_product_train <- fread('data/order_products__train.csv')

# Filtering orders on only "train"
train_allorders <- subset(orders,eval_set=="train",select=c("order_id"))

# Getting the actual reorders for "train" orders
train_reordered <- order_product_train %>%  filter(reordered == 1) %>%
                            group_by(order_id) %>% summarise(products=paste(product_id,collapse=" ")) 

# Merging with all "train" orders to get empty reordered orders
train_ground_truth <- merge(train_allorders,train_reordered, all.x=T,by="order_id")
train_ground_truth$products[is.na(train_ground_truth$products)] <- 'None'

rm(train_allorders,train_reordered)

# Function to get F1 Score on Train
get_f1_train <- function(pred){
  act <- subset(train_ground_truth, order_id %in% pred$order_id )
  act$products <- trimws(act$products)
  pred$products <- trimws(pred$products)
  temp <- merge(act,pred)
  print(head(act, 20))
  print(head(pred, 20))
  temp$n_act <- lapply(strsplit(temp$products.x," "),length)
  temp$n_pred <- lapply(strsplit(temp$products.y," "),length)
  temp$comb <- paste(temp$products.x,temp$products.y,sep=" ")
  temp$n_common <- lapply(strsplit(temp$comb,split=" "), function(x)sum(duplicated(x)) )
 
  temp$precision <- as.numeric(temp$n_common)/as.numeric(temp$n_pred)
  temp$recall <- as.numeric(temp$n_common)/as.numeric(temp$n_act)
  temp$f1 <- ifelse(temp$precision + temp$recall >0, 2 * temp$precision * temp$recall / (temp$precision + temp$recall),0)
  return(mean(temp$f1))
} 
```
```{r}
# Testing the function 
pred <- submission

ptm <- proc.time()
    res <- get_f1_train(pred)
proc.time() - ptm
res
```

